#! /bin/sh
# Clone the iStore-Marketing Repo into Library
git clone https://github.com/core-group/iStores.git /Shared Items/Techs/iStore_Marketing
# Copy LaunchDaemon
cp /Library/iStores/com.core.istore.RunGitPull.plist /Library/LaunchDaemons/
launchctl load -w /Library/LaunchDaemons/
